[settings]
dotfiles.default_mode = "symlink-each"

[bootstrap.files."/etc/greetd/config.toml"]
owner = "root"
group = "root"
mode = "644"
content = '''
[terminal]
# The VT to run the greeter on.
vt = 7

# The default session, also known as the greeter.
[default_session]
command = "tuigreet"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "_greeter"
'''

# Dependency of ddcutil
[bootstrap.files."/etc/modules-load.d/i2c-dev.conf"]
owner = "root"
group = "root"
mode = "644"
content = "i2c-dev"

[bootstrap.directories."/usr/local/share/wayland-sessions"]
owner = "root"
group = "root"
mode = "755"

# Start niri wrapped in dbus-run-session since we don't use systemd
[bootstrap.files."/usr/local/share/wayland-sessions/niri.desktop"]
owner = "root"
group = "root"
mode = "644"
content = '''
[Desktop Entry]
Name=Niri (with dbus)
Type=Application
DesktopNames=niri
Exec=dbus-run-session niri --session
'''

# https://www.januschka.com/chromium-omarchy.html
[bootstrap.directories."/etc/brave"]
owner = "root"
group = "root"
mode = "755"

# https://www.januschka.com/chromium-omarchy.html
[bootstrap.directories."/etc/brave/policies"]
owner = "root"
group = "root"
mode = "755"

# https://www.januschka.com/chromium-omarchy.html
[bootstrap.directories."/etc/brave/policies/managed"]
owner = "root"
group = "root"
mode = "755"

[bootstrap.files."/etc/iwd/main.conf"]
owner = "root"
group = "root"
mode = "644"
content = '''
[General]
# Use iwd's internal dhcp client
EnableNetworkConfiguration=true
'''

# [bootstrap.directories."/etc/NetworkManager/conf.d"]
# owner = "root"
# group = "root"
# mode = "755"

# # Use cloudflare's DNS servers for all connections
# [bootstrap.files."/etc/NetworkManager/conf.d/00-global-dns.conf"]
# owner = "root"
# group = "root"
# mode = "644"
# content = '''
# [global-dns-domain-*]
# servers=1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001
# '''

[dotfiles]
"~/.config/fish" = { source = "./.config/fish" }
"~/.config/foot" = { source = "./.config/foot" }
"~/.config/niri" = { source = "./.config/niri" }
"~/.config/noctalia" = { source = "./.config/noctalia" }

[bootstrap.user]
login_shell = "/usr/bin/fish"
