[bootstrap.packages]
"brew:bfg" = "latest"
"brew:coreutils" = "latest"
"brew:eza" = "latest"
"brew:fzf" = "latest"
"brew:gh" = "latest"
"brew:git" = "latest"
"brew:git-delta" = "latest"
"brew:git-filter-repo" = "latest"
"brew:git-get" = "latest"
"brew:git-lfs" = "latest"
"brew:gpg" = "latest"
"brew:hub" = "latest"
"brew:neovim" = "latest"
"brew:node" = "latest"
"brew:pinentry-mac" = "latest"
"brew:rust" = "latest"
