# Install homebrew first and use normally. Following are some useful commands:
# - brew uninstall <formula_name>
# - brew autoremove
[bootstrap.brew]
adopt = true

[bootstrap.packages]
"brew-cask:balenaetcher" = "latest"
"brew-cask:betterdisplay" = "latest"
"brew-cask:brave-browser" = "latest"
"brew-cask:calibre" = "latest"
"brew-cask:docker-desktop" = "latest"
"brew-cask:font-fira-code" = "latest"
"brew-cask:handbrake-app" = "latest"
"brew-cask:kitty" = "latest"
"brew-cask:nordvpn" = "latest"
"brew-cask:pritunl" = "latest"
"brew-cask:redis-insight" = "latest"
"brew-cask:slack" = "latest"
"brew-cask:studio-3t" = "latest"
"brew-cask:transmission" = "latest"
"brew-cask:ungoogled-chromium" = "latest"
"brew:ast-grep" = "latest"
"brew:bfg" = "latest"
"brew:coreutils" = "latest"
"brew:diffutils" = "latest"
"brew:dua-cli" = "latest"
"brew:duf" = "latest"
"brew:emmylua_ls" = "latest"
"brew:eza" = "latest"
"brew:fd" = "latest"
"brew:findutils" = "latest"
"brew:fish" = "latest"
"brew:gh" = "latest"
"brew:git" = "latest"
"brew:git-delta" = "latest"
"brew:git-filter-repo" = "latest"
"brew:git-get" = "latest"
"brew:git-lfs" = "latest"
"brew:gnu-sed" = "latest"
"brew:gnupg" = "latest"
"brew:grep" = "latest"
"brew:htop" = "latest"
"brew:hub" = "latest"
"brew:jq" = "latest"
"brew:less" = "latest"
"brew:moor" = "latest"
"brew:openssh" = "latest"
"brew:pass" = "latest"
"brew:pass-otp" = "latest"
"brew:qrencode" = "latest"
"brew:ripgrep" = "latest"
"brew:sevenzip" = "latest"
"brew:shfmt" = "latest"
"brew:starship" = "latest"
"brew:tailwindcss-language-server" = "latest"
"brew:tokei" = "latest"
"brew:trash-cli" = "latest"
"brew:tree-sitter-cli" = "latest"
"brew:unzip" = "latest"
"brew:wget" = "latest"
"brew:worktrunk" = "latest"
"brew:yt-dlp" = "latest"
"brew:zoxide" = "latest"

[dotfiles]
"~/.local/bin" = { source = "./macos/.local/bin" }
"~/.config/kitty" = { source = "./macos/.config/kitty" }

[bootstrap.macos.launchd.agents.session-env]
program = "$HOME/.local/bin/session-env.sh"
run_at_load = true

[bootstrap.user]
login_shell = "/opt/homebrew/bin/fish"
