# See https://sw.kovidgoyal.net/kitty/conf.html

shell_integration disabled
active_border_color none
active_tab_font_style bold
clear_all_shortcuts yes
copy_on_select yes
cursor_beam_thickness 2
cursor_blink_interval 0
enabled_layouts splits,stack
hide_window_decorations yes
kitty_mod cmd
macos_colorspace default
macos_option_as_alt yes
macos_quit_when_last_window_closed yes
strip_trailing_spaces smart
symbol_map U+e000-U+e00a,U+e0a0-U+e0a2,U+e0a3,U+e0b0-U+e0b3,U+e0b4-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ea60-U+ec1e,U+ed00-U+efce,U+f000-U+f2ff,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font Mono
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
text_composition_strategy legacy
url_style single

map kitty_mod+0 change_font_size all 0
map kitty_mod+[ previous_tab
map kitty_mod+] next_tab
map kitty_mod+c copy_to_clipboard
map kitty_mod+ctrl+f toggle_fullscreen
map kitty_mod+ctrl+m toggle_maximized
map kitty_mod+enter launch --cwd=current --location=vsplit
map kitty_mod+equal change_font_size all +1.0
map kitty_mod+h neighboring_window left
map kitty_mod+j neighboring_window down
map kitty_mod+k neighboring_window up
map kitty_mod+l neighboring_window right
map kitty_mod+left previous_tab
map kitty_mod+minus change_font_size all -1.0
map kitty_mod+n new_os_window
map kitty_mod+o toggle_layout stack
map kitty_mod+r load_config_file
map kitty_mod+right next_tab
map kitty_mod+s goto_session
map kitty_mod+shift+[ move_tab_backward
map kitty_mod+shift+] move_tab_forward
map kitty_mod+shift+enter launch --cwd=current --location=hsplit
map kitty_mod+shift+h move_window left
map kitty_mod+shift+j move_window down
map kitty_mod+shift+k move_window up
map kitty_mod+shift+l move_window right
map kitty_mod+shift+s save_as_session --use-foreground-process --base-dir ~/.local/share/kitty/sessions
map kitty_mod+t new_tab_with_cwd
map kitty_mod+v paste_from_clipboard
map kitty_mod+w close_tab
map kitty_mod+x close_window

undercurl_style thick-sparse
modify_font underline_position 2
modify_font underline_thickness 100%
modify_font cell_width -1px

font_family postscript_name=FiraCode-Regular
bold_font postscript_name=FiraCode-Bold
italic_font postscript_name=FiraCode-Regular
bold_italic_font postscript_name=FiraCode-Bold

# font_size 14
# modify_font cell_height 15px

font_size 15
modify_font cell_height 13px

foreground                      #2C363C
background                      #E8E4E3
selection_foreground            #2C363C
selection_background            #CBD9E3
cursor                          #2C363C
cursor_text_color               #F0EDEC
active_tab_foreground           #2C363C
active_tab_background           #DEB9D6
inactive_tab_foreground         #2C363C
inactive_tab_background         #D6CDC9

# black
color0 #F0EDEC
color8 #CFC1BA
# red
color1 #A8334C
color9 #94253E
# green
color2  #4F6C31
color10 #3F5A22
# yellow
color3  #944927
color11 #803D1C
# blue
color4  #286486
color12 #1D5573
# magenta
color5  #88507D
color13 #7B3B70
# cyan
color6  #3B8992
color14 #2B747C
# white
color7  #2C363C
color15 #4F5E68
