include ~/.local/state/omarchy/current/theme/kitty.conf

font_family postscript_name=FiraCode-Regular
bold_font postscript_name=FiraCode-Bold
italic_font postscript_name=FiraCode-Regular
bold_italic_font postscript_name=FiraCode-Bold

font_size 11
modify_font cell_height 7px
