[tools]
# Dev
go = "latest"
rust = "latest"
node = "latest"
python = "latest"
# Agents
pi = "latest"
claude-code = "latest"

[shell_alias]
cc = "SHELL=/bin/bash command claude"
cp = "cp -i"
df = "duf"
diff = "diff --color=auto"
du = "dua"
g = "git"
less = "moor"
ls = "eza -ah --group-directories-first --icons=auto"
l = "ls -l"
l1 = "ls -L1 -T -I .git"
l2 = "l1 -L2"
l3 = "l1 -L3"
l4 = "l1 -L4"
l5 = "l1 -L5"
p = "pnpm"
tp = "trash-put"
vi = "nvim"
y = "yarn"
# rm = 'echo '\''Use `trash-put` instead!'\'' false'

[env]
EDITOR = "nvim"
VISUAL = "nvim"
PAGER = "moor"
MANPAGER = "moor"
MOOR = "--no-linenumbers --terminal-fg"
PASSWORD_STORE_DIR = "$HOME/Projects/github.com/stellarhoof/pass"
