[tools]
neovim = "nightly"
go = "latest"
rust = "latest"
node = "latest"
python = "latest"
pi = "latest"
claude-code = "latest"

[shell_alias]
cc = "SHELL=/bin/bash command claude"
cp = "cp -i"
df = "duf"
diff = "diff --color=auto"
du = "dua"
eza = "eza --icons --group-directories-first"
g = "git"
l = "eza -la"
la = "eza -a"
less = "less -R"
ll = "eza -l"
lla = "eza -la"
ls = "eza"
lt = "eza --tree"
p = "pnpm"
tp = "trash-put"
vi = "nvim"
y = "yarn"
# rm = 'echo '\''Use `trash-put` instead!'\'' false'

[env]
EDITOR = "nvim"
VISUAL = "nvim"
PAGER = "less -R"
MANPAGER = "less -s -M"
GROFF_NO_SGR = 1
PASSWORD_STORE_DIR = "$HOME/Projects/github.com/stellarhoof/pass"
