[tools]
codex = "latest"
go = "latest"
node = "latest"
rust = "latest"

# pnpm = "latest"
# yarn = "latest"
# "npm:@vtsls/language-server" = "latest"

[shell_alias]
# Programs
cp = "cp -i"
df = "duf"
diff = "diff --color=auto"
du = "dua"
g = "git"
less = "less -R"
tp = "trash-put"
vi = "nvim"
rm = "echo 'Use trash-put instead!'"
# Tools
p = "pnpm"
y = "yarn"
# Listing
ls = "eza -ah --group-directories-first --icons=auto"
l = "ls -l"
lt = "eza -h --tree --level=2 --icons=auto"
lta = "lt -a"
# Agents
co = "SHELL=/bin/bash opencode --auto"
cx = "SHELL=/bin/bash command claude --permission-mode bypassPermissions"
cy = "SHELL=/bin/bash command codex -s danger-full-access -a never"

[env]
# Default programs
EDITOR = "nvim"
VISUAL = "nvim"
PAGER = "less -R"
MANPAGER = "less -s -M"
RIPGREP_CONFIG_PATH = "$XDG_CONFIG_HOME/ripgrep/ripgreprc"
PASSWORD_STORE_DIR = "~/Projects/github.com/stellarhoof/pass"
# Home declutter
# CARGO_HOME = "$XDG_DATA_HOME/cargo"
# GOMODCACHE = "$XDG_CACHE_HOME/go/mod"
# GOPATH = "$XDG_DATA_HOME/go"
# NODE_REPL_HISTORY = "$XDG_STATE_HOME/node_repl_history"
# NPM_CONFIG_USERCONFIG = "$XDG_CONFIG_HOME/npm/npmrc.user"
# NPM_CONFIG_GLOBALCONFIG = "$XDG_CONFIG_HOME/npm/npmrc"
# PYTHONPYCACHEPREFIX = "$XDG_CACHE_HOME/python"
# PYTHON_EGG_CACHE = "$XDG_CACHE_HOME/python-eggs"
# PYTHON_HISTORY = "$XDG_STATE_HOME/python_history"
# RUSTUP_HOME = "$XDG_DATA_HOME/rustup"
# ICEAUTHORITY = "$XDG_CACHE_HOME/ICEauthority"
# INPUTRC = "$XDG_CONFIG_HOME/readline/inputrc"
# MYSQL_HISTFILE = "$XDG_STATE_HOME/mysql_history"
# REDISCLI_HISTFILE = "$XDG_STATE_HOME/redis/rediscli_history"
# REDISCLI_RCFILE = "$XDG_CONFIG_HOME/redis/redisclirc"
# SQLITE_HISTORY = "$XDG_STATE_HOME/sqlite_history"
# GROFF_NO_SGR = 1
# EXA_ICON_SPACING = 2
