[settings]
dotfiles.default_mode = "symlink-each"

[bootstrap.packages]
"pacman:7zip" = "latest"
"pacman:ast-grep" = "latest"
"pacman:dua-cli" = "latest"
"pacman:duf" = "latest"
"pacman:fish" = "latest"
"pacman:git-delta" = "latest"
"pacman:git-filter-repo" = "latest"
"pacman:git-lfs" = "latest"
"pacman:htop" = "latest"
"pacman:hub" = "latest"
"pacman:moor" = "latest"
"pacman:pass" = "latest"
"pacman:pass-otp" = "latest"
"pacman:qrencode" = "latest"
"pacman:shfmt" = "latest"
"pacman:tailwindcss-language-server" = "latest"
"pacman:tokei" = "latest"
"pacman:trash-cli" = "latest"
"pacman:ttf-fira-code" = "latest"
"pacman:wget" = "latest"
"pacman:worktrunk" = "latest"

[bootstrap.repos]
"~/Projects/github.com/stellarhoof/nvim" = { url = "https://github.com/stellarhoof/nvim.git" }
"~/Projects/github.com/stellarhoof/pass" = { url = "https://github.com/stellarhoof/pass.git" }

# [bootstrap.hooks.post-repos]
# run = [
#   '''
# # Change neovim's repo remote origin
# cd ~/Projects/github.com/stellarhoof/nvim
# git remote set-url origin git@github.com:stellarhoof/nvim.git
#
# # Change pass's repo remote origin
# cd ~/Projects/github.com/stellarhoof/pass
# git remote set-url origin git@github.com:stellarhoof/pass.git
#
# # Import gpg key used to un-encrypt passwords
# gpg --batch --import store-key.asc
#
# # Trust imported gpg key
# fingerprint=$(gpg --batch --with-colons --fingerprint "azure.satellite@gmail.com" | awk -F: '/^fpr/{print $10; exit}')
# echo "${fingerprint}:4:" | gpg --batch --import-ownertrust
#
# # Add github's SSH key to ssh agent
# mkdir -p ~/.ssh
# pass ssh/github.com > ~/.ssh/github.com
# chmod 600 ~/.ssh/github.com
# ssh-add ~/.ssh/github.com
# ''',
# ]

[dotfiles]
"~/.ssh" = { source = "./.ssh" }
"~/.config" = { source = "../unix/.config" }
"~/.config/fish" = { source = "./.config/fish" }
"~/.config/kitty" = { source = "./.config/kitty" }
"~/.config/nvim" = { source = "~/Projects/github.com/stellarhoof/nvim", mode = "symlink" }

[bootstrap.user]
login_shell = "/usr/bin/fish"
