[settings]
dotfiles.default_mode = "symlink-each"

[bootstrap.packages]
"pacman:7zip" = "latest"
"pacman:ast-grep" = "latest"
"pacman:dua-cli" = "latest"
"pacman:duf" = "latest"
"pacman:fish" = "latest"
"pacman:git-delta" = "latest"
"pacman:git-filter-repo" = "latest"
"pacman:git-lfs" = "latest"
"pacman:htop" = "latest"
"pacman:hub" = "latest"
"pacman:moor" = "latest"
"pacman:pass" = "latest"
"pacman:pass-otp" = "latest"
"pacman:qrencode" = "latest"
"pacman:shfmt" = "latest"
"pacman:tailwindcss-language-server" = "latest"
"pacman:tokei" = "latest"
"pacman:trash-cli" = "latest"
"pacman:wget" = "latest"
"pacman:worktrunk" = "latest"

[bootstrap.repos]
"~/Projects/github.com/stellarhoof/nvim" = { url = "https://github.com/stellarhoof/nvim.git" }
"~/Projects/github.com/stellarhoof/pass" = { url = "https://github.com/stellarhoof/pass.git" }

[dotfiles]
"~/.ssh" = { source = "./.ssh" }
"~/.config" = { source = "../unix/.config" }
"~/.config/fish" = { source = "./.config/fish" }
"~/.config/kitty" = { source = "./.config/kitty" }
"~/.config/mise" = { source = "./.config/mise" }
"~/.config/nvim" = { source = "~/Projects/github.com/stellarhoof/nvim", mode = "symlink" }

[bootstrap.user]
login_shell = "/usr/bin/fish"
